# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Backend Install
          command: |
            npm run backend:install
      - run:
          name: Backend Build
          command: |
            npm run backend:build
      - run:
          name: Frontend Install
          command: |
            npm run frontend:install
      - run:
          name: Frontend Build
          command: |
            npm run frontend:build
